language: cpp

matrix:
  include:
    - os: linux
      compiler: gcc
      dist: xenial
      sudo: required
      env:
        - BUILD_NAME=xenial

    - os: osx
      compiler: clang
      env:
        - BUILD_NAME=osx

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get -qq update; fi
#  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew upgrade; fi
# Homebrew upgrade disabled to save time.

install:
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]];
      then 
          sudo apt-get install build-essential git cmake qt5-default libpng-dev libnova-dev libproj-dev zlib1g-dev libbz2-dev libopenjp2-7-dev qttools5-dev-tools qttools5-dev;
      fi
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew tap indilib/indi; brew install git cmake libnova openjpeg libpng qt5; export PATH="/usr/local/opt/qt5/bin:$PATH";  echo 'export PATH="/usr/local/opt/qt5/bin:$PATH"' >> ~/.bash_profile; fi

script:
    - mkdir build && cd build
    - cmake ..
    - make -s

notifications:
    email: false
    
git:
    depth: 10
